-- =============================================================
-- Workmate 도메인 테이블 스키마
-- 컨테이너 최초 기동 시 docker-entrypoint-initdb.d 에서 01-init.sql 다음에 자동 실행된다.
-- 이미 볼륨이 있는 기존 환경에 수동 적용:
--   (WSL)  docker exec -i workmate-db psql -U workmate -d workmate_db < db/init/02-schema.sql
-- 규칙: 소문자 snake_case, 테이블명 단수형, 제약조건은 테이블명_컬럼명_제약 (~_pk / ~_uk / idx_~)
-- =============================================================

-- 영수증 OCR 결과 저장 테이블 (Phase 2)
CREATE TABLE IF NOT EXISTS receipt (
    receipt_seq   bigint GENERATED BY DEFAULT AS IDENTITY,  -- 영수증 식별자 (PK)
    user_seq      bigint       NOT NULL,                    -- 등록 사용자 식별자
    image_path    varchar(512) NOT NULL,                    -- 업로드 이미지 저장 경로
    pay_amount    integer      NOT NULL,                    -- 결제 금액 (원)
    biz_no        varchar(10)  NOT NULL,                    -- 사업자등록번호 10자리 (하이픈 없음)
    pay_date      varchar(8)   NOT NULL,                    -- 결제일 YYYYMMDD
    card_name     varchar(100),                             -- 결제 카드사명
    biz_no_valid  boolean      NOT NULL,                    -- 사업자번호 체크섬 검증 통과 여부
    select_type   varchar(10)  NOT NULL,                    -- 카드 매핑 방식 (AUTO/MANUAL)
    raw_json      jsonb,                                    -- OCR 원본 응답 JSON
    created_at    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT receipt_receipt_seq_pk PRIMARY KEY (receipt_seq)
);

-- 사용자별 최신순 이력 조회 최적화 인덱스
CREATE INDEX IF NOT EXISTS idx_receipt_user_created ON receipt (user_seq, created_at DESC);

-- 가이드 문서 원본 테이블 (Phase 3 — RAG 근거 자료)
CREATE TABLE IF NOT EXISTS guide (
    guide_seq   bigint GENERATED BY DEFAULT AS IDENTITY,    -- 가이드 문서 식별자 (PK)
    user_seq    bigint       NOT NULL,                      -- 작성자 식별자
    title       varchar(255) NOT NULL,                      -- 문서 제목
    content     text         NOT NULL,                      -- 문서 본문 (마크다운)
    is_public   boolean      NOT NULL DEFAULT true,         -- 공개 여부
    created_at  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT guide_guide_seq_pk PRIMARY KEY (guide_seq)
);

-- Spring AI PgVectorStore 표준 스키마 (initialize-schema: false 이므로 여기서 직접 관리)
-- embedding 차원 768 = Gemini text-embedding-004 출력 차원과 일치해야 한다
CREATE TABLE IF NOT EXISTS vector_store (
    id        uuid NOT NULL,       -- 청크 식별자 (Spring AI가 UUID 발급)
    content   text,                -- 분할된 청크 본문
    metadata  jsonb,               -- guideSeq/title/isPublic 등 출처 메타데이터
    embedding vector(768),         -- 임베딩 벡터
    CONSTRAINT vector_store_id_pk PRIMARY KEY (id)
);

-- 코사인 유사도 검색 최적화를 위한 HNSW 인덱스
CREATE INDEX IF NOT EXISTS idx_vector_store_embedding
    ON vector_store USING hnsw (embedding vector_cosine_ops);
