-- =============================================================
-- 마일스톤 1 테이블: 인증(admin_user)·채팅(chat_room/chat_message)·감사(admin_audit_log)
-- 이미 볼륨이 있는 기존 환경에 수동 적용:
--   wsl -e sh -c "cd /mnt/c/ClaudeCode/workmate-ws/workmate && docker exec -i workmate-db psql -U workmate -d workmate_db < db/init/03-schema.sql"
-- 규칙: 소문자 snake_case, 단수형, 제약 테이블명_컬럼명_제약 (04 문서 §4)
-- =============================================================

-- 회원 (04 §4.1) — email/phone 은 AES-256 암호문 저장 (email 은 결정적 암호화라 UK 유효)
CREATE TABLE IF NOT EXISTS admin_user (
    user_seq          bigint GENERATED BY DEFAULT AS IDENTITY,
    email             varchar(512) NOT NULL,             -- AES-256 암호문 (소문자 정규화 후 암호화 — F9-01)
    password          varchar(60)  NOT NULL,             -- BCrypt 해시
    user_name         varchar(50)  NOT NULL,
    phone             varchar(512),                      -- AES-256 암호문
    role              varchar(20)  NOT NULL DEFAULT 'ROLE_USER',
    login_fail_count  integer      NOT NULL DEFAULT 0,   -- F1-06
    locked_at         timestamp,                         -- 잠금 시각 (+1시간 후 자동 해제)
    use_yn            boolean      NOT NULL DEFAULT true,
    created_at        timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_user_user_seq_pk PRIMARY KEY (user_seq),
    CONSTRAINT admin_user_email_uk UNIQUE (email)
);

-- 채팅방 (04 §4.2) — 1-B 에서 사용하지만 DB 변경은 한 번에
CREATE TABLE IF NOT EXISTS chat_room (
    room_seq    bigint GENERATED BY DEFAULT AS IDENTITY,
    user_seq    bigint       NOT NULL,
    title       varchar(100) NOT NULL,
    use_yn      boolean      NOT NULL DEFAULT true,
    created_at  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chat_room_room_seq_pk PRIMARY KEY (room_seq)
);
CREATE INDEX IF NOT EXISTS idx_chat_room_user ON chat_room (user_seq, created_at DESC);

CREATE TABLE IF NOT EXISTS chat_message (
    message_seq  bigint GENERATED BY DEFAULT AS IDENTITY,
    room_seq     bigint      NOT NULL,
    role         varchar(10) NOT NULL,                   -- 'user' | 'assistant'
    content      text        NOT NULL,
    model_name   varchar(50),
    created_at   timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chat_message_message_seq_pk PRIMARY KEY (message_seq)
);
CREATE INDEX IF NOT EXISTS idx_chat_message_room ON chat_message (room_seq, created_at);

-- 관리자 감사 로그 (04 §4.6) — append-only, UPDATE/DELETE 금지
CREATE TABLE IF NOT EXISTS admin_audit_log (
    audit_seq        bigint GENERATED BY DEFAULT AS IDENTITY,
    admin_user_seq   bigint      NOT NULL,
    target_user_seq  bigint      NOT NULL,
    action           varchar(30) NOT NULL,               -- 'UNLOCK' | 'RESET_PASSWORD'
    created_at       timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_audit_log_audit_seq_pk PRIMARY KEY (audit_seq)
);
